import React from "react";
import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Aboutus",
  description: "Generated by Maimoona Masood",
  icons: {
    icon: {
      url: "images/logo.png",
      type: "image.png",
    },
  },
};

const Aboutus = () => {
  return (
    <div>
      <div className="container mx-auto px-4 mt-10 mb-20">
        {/* About Us Section */}
        <div className="flex flex-col lg:flex-row items-center gap-10 lg:gap-5 mt-10">
          <div className="bg-[#007580] lg:w-1/2 lg:h-[470px] p-10">
            <h1 className="font-bold text-3xl text-white mb-5">
              About Us - Comforty
            </h1>
            <p className="text-white text-lg mb-10">
              At Comforty, we believe that the right chair can transform your
              space and elevate your comfort. Specializing in ergonomic design,
              premium materials, and modern aesthetics, we craft chairs that
              seamlessly blend style with functionality.
            </p>
            <button className="bg-[#007580] hover:bg-[#459494] text-white border border-white py-3 px-8 rounded">
              View Collection
            </button>
          </div>
          <div className="lg:w-1/2  bg-red-400">
            <Image
              src="/images/whitechair2.png"
              alt="whitechair"
              width={619}
              height={200}
              className=""
            />
          </div>
        </div>

        {/* What Makes Us Different Section */}
        <div className="mt-24 text-center">
          <h2 className="font-semibold text-2xl lg:text-3xl text-[#272343]">
            What makes Our Brand different?
          </h2>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mt-14">
          {/* Card 1 */}
          <div className="bg-[#F9F9F9] p-5 text-center">
            <div className="mb-3">
              <Image src="/images/car.png" alt="car" height={24} width={24} />
            </div>
            <h3 className="text-[#007580] font-medium text-lg mb-3">
              Next day as standard
            </h3>
            <p className="text-[#007580] text-base">
              Order before 3pm and get your order the next day as standard.
            </p>
          </div>
          {/* Card 2 */}
          <div className="bg-[#F9F9F9] p-5 text-center">
            <div className="mb-3">
              <Image
                src="/images/tick2.png"
                alt="tick"
                height={24}
                width={24}
              />
            </div>
            <h3 className="text-[#007580] font-medium text-lg mb-3">
              Made by true artisans
            </h3>
            <p className="text-[#007580] text-base">
              Handmade crafted goods made with real passion and craftsmanship.
            </p>
          </div>
          {/* Card 3 */}
          <div className="bg-[#F9F9F9] p-5 text-center">
            <div className="mb-3">
              <Image
                src="/images/price.png"
                alt="price"
                height={24}
                width={24}
              />
            </div>
            <h3 className="text-[#007580] font-medium text-lg mb-3">
              Unbeatable prices
            </h3>
            <p className="text-[#007580] text-base">
              For our materials and quality, you won’t find better prices
              anywhere.
            </p>
          </div>
          {/* Card 4 */}
          <div className="bg-[#F9F9F9] p-5 text-center">
            <div className="mb-3">
              <Image
                src="/images/flower.png"
                alt="flower"
                height={24}
                width={24}
              />
            </div>
            <h3 className="text-[#007580] font-medium text-lg mb-3">
              Recycled packaging
            </h3>
            <p className="text-[#007580] text-base">
              We use 100% recycled materials to ensure our footprint is more
              manageable.
            </p>
          </div>
        </div>
      </div>

      <div className="ml-10 font-inter font-semibold text-3xl text-[#272343] ">
        Our Popular products
      </div>
      <div className="flex flex-col md:flex-row gap-5 px-10 mt-10 font-inter mb-20">
        <div>
          <Image
            src="/images/bigsofa.png"
            alt="Greensofa"
            height={375}
            width={630}
          />
          <div className="py-3">
            <div className="font-normal text-[#2A254B] text-lg">
              The Poplar suede sofa
            </div>
            <div className="font-bold text-sm">£99</div>
          </div>
        </div>

        <div>
          <Image
            src="/images/blackchair.png"
            alt="Greensofa"
            height={375}
            width={305}
          />
          <div className="py-3">
            <div className="font-normal text-[#2A254B] text-lg">
              The Dandy Chair
            </div>
            <div className="font-bold text-sm">£99</div>
          </div>
        </div>
        <div>
          <Image
            src="/images/dandychair.png"
            alt="dandychair"
            height={375}
            width={305}
          />
          <div className="py-3">
            <div className="font-normal text-[#2A254B] text-lg">
              The Dandy Chair
            </div>
            <div className="font-bold text-sm">£99</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Aboutus;
