import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import Navbar2 from "./components/Navbar2";
import Footer from "./components/Footer";



const inter = Inter({ subsets: ["latin"], 
  weight: ["200","400","600"]
});

export const metadata: Metadata = {
  title: "Comforty",
  description: "Generated by Maimoona Masood",
  icons: {
    icon: {
      url: "images/logo.png",
      type: "image.png"
    }
    }
  };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <br />
        <Navbar/>
        <Navbar2/>
       <div className="">{children}</div> 
       <Footer/>
        
        </body>
    </html>
  );
}
