import React from 'react'
import Image from 'next/image'
import type { Metadata } from "next";
import Link from 'next/link';
import Subscribe from '../subscribe/page';


export const metadata: Metadata = {
  title: "product",
  description: "Generated by Maimoona Masood",
  icons: {
    icon: {
      url: "images/logo.png",
      type: "image.png"
    }
    }
  };


const product = () => {
  return (
    <div>
      <div className=" lg:pb-[80px]  lg:w-[83%] mx-auto mt-16">
      {/* Title */}
      <div className="text-2xl pb-[40px] text-center lg:text-left">
        <h1 className='font-inter font-semibold text-[32px] text-[#272343]'>All Products</h1>
      </div>

      {/* Products Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 mt-8">
        {/* Product Card 1 */}
        <div className="relative w-full">
          {/* Status Badge */}
          <div className="absolute top-2 left-2 bg-[#01AD5A] text-white text-xs font-medium capitalize px-2 py-1 rounded-[4px]">
            New
          </div>

          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/whitechair.png"
              alt="chair1"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 2 */}
        <div className="relative w-full">
          {/* Status Badge */}
          <div className="absolute top-2 left-2 bg-orange-500 text-white text-xs font-medium capitalize px-2 py-1 rounded-[4px]">
            New
          </div>

          {/* Product Image */}
          <Link href="/product/chairs"><div className="flex justify-center items-center">
            <Image
              src="/images/pinkchair.png"
              alt="chair2"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>
          </Link>
          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 3 */}
        <div className="relative w-full">
          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/orangechair.png"
              alt="chair3"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 4 */}
        <div className="relative w-full">
          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/white.png"
              alt="chair4"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>
      </div>
    </div>

{/* second line */}
<div className=" lg:w-[83%] mx-auto lg:pb-[80px] pb-10">
      {/* Products Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {/* Product Card 1 */}
        <div className="relative w-full">
          {/* Status Badge */}
          <div className="absolute top-2 left-2 bg-[#01AD5A] text-white text-xs font-medium capitalize px-2 py-1 rounded-[4px]">
            New
          </div>

          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/stool.png"
              alt="chair5"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 2 */}
        <div className="relative w-full">
          {/* Status Badge */}
          <div className="absolute top-2 left-2 bg-orange-500 text-white text-xs font-medium capitalize px-2 py-1 rounded-[4px]">
            New
          </div>

          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/grey.png"
              alt="chair6"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 3 */}
        <div className="relative w-full">
          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/greenchair.png"
              alt="chair7"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 4 */}
        <div className="relative w-full">
          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/whitechair.png"
              alt="chair8"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>
      </div>
    </div>

    {/* third line */}
    <div className=" lg:w-[83%] mx-auto ">

      {/* Products Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {/* Product Card 1 */}
        <div className="relative w-full">
          {/* Status Badge */}
          <div className="absolute top-2 left-2 bg-[#01AD5A] text-white text-xs font-medium capitalize px-2 py-1 rounded-[4px]">
            New
          </div>

          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/wingchair.png"
              alt="chair9"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 2 */}
        <div className="relative w-full">
          {/* Status Badge */}
          <div className="absolute top-2 left-2 bg-orange-500 text-white text-xs font-medium capitalize px-2 py-1 rounded-[4px]">
            New
          </div>

          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/pinkchair.png"
              alt="chair10"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 3 */}
        <div className="relative w-full">
          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/orangechair.png"
              alt="chair11"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>

        {/* Product Card 4 */}
        <div className="relative w-full">
          {/* Product Image */}
          <div className="flex justify-center items-center">
            <Image
              src="/images/black.png"
              alt="chair12"
              height={312}
              width={312}
              className="w-full h-auto rounded-lg"
            />
          </div>

          {/* Product Details */}
          <div className="mt-3">
            <h3 className="text-sm font-medium text-gray-800 hover:text-[#007580]">
              Library Stool Chair
            </h3>
            <p className="text-sm font-medium text-gray-800">$20</p>
          </div>

          {/* Add to Cart Button */}
          <button className="absolute bottom-2 right-2 bg-[#F0F2F3] hover:bg-[#007580] text-white p-2 rounded-md">
            <Image
              src="/images/cart.png"
              alt="cart"
              width={22}
              height={22}
            />
          </button>
        </div>
      </div>
    </div>
      

    {/* subscribe portion */}
      <Subscribe/>
</div>
  )
}

export default product
